settings:
  indexPerPage: 36

tasks:
  # - example1:
  #   usePictrue: True
  #   totalNum: 200
  #   criterion:
  #     - Justification: 4 # num 4 means [0,1,2,3]

  # - example2:
  #   usePictrue: False
  #   totalNum: 800
  #   criterion:
  #     - Coherence: 4
  #     - Informativeness: 4
  #     - Fluency: 4
  #     - Overall: 4

  VCR:
    author: 'Yuan Fan'
    usePictrue: True
    totalNum: 200
    datasetPath: 'static/resources/VCRref.json'
    criterion:
      - Justification: 4 # num 4 means [0,1,2,3]
  
  QA:
    author: 'Ni Xuanfan'
    usePictrue: False
    totalNum: 800
    datasetPath: 'static/resources/QAref.json'
    criterion:
      - Coherence: 4
      - Informativeness: 4
      - Fluency: 4
      - Overall: 4