settings:
  indexPerPage: 36

tasks:
  taskWithPicture:
    author: 'Anonymous'
    usePicture: True
    totalNum: 5
    datasetPath: 'static/resources/taskWithPictureRef.json'
    criterion:
      - Justification: 4 # num 4 means [0,1,2,3]
  
  taskWithoutPicture:
    author: 'Anonymous'
    usePicture: False
    totalNum: 5
    datasetPath: 'static/resources/taskWithoutPictureRef.json'
    criterion:
      - Coherence: 4
      - Informativeness: 4
      - Fluency: 4
      - Overall: 3